# Generated by Django 5.1 on 2024-12-17 17:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام محصول')),
                ('zirname', models.CharField(blank=True, max_length=50, null=True, verbose_name='محصول نول دارد؟')),
                ('faz', models.CharField(max_length=50, verbose_name='مقدار فاز ')),
                ('power', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='قدرت قطع')),
                ('isnew', models.BooleanField(default=False, verbose_name='آیا محصول جدید است؟')),
                ('creatat', models.DateTimeField(auto_now_add=True)),
                ('discount', models.BooleanField(default=False, verbose_name='آیا محصول تخفیف دارد؟')),
                ('discountpercentage', models.PositiveIntegerField(default=0, verbose_name='درصد تخفیف چقدر است؟')),
                ('discountutil', models.DateTimeField(blank=True, null=True, verbose_name='مدت زمان تخفیف چفدر است؟')),
                ('price', models.IntegerField(verbose_name='قیمت محصول چقدر است؟')),
                ('discountprice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='قیمت محصول بعد از تخفیف')),
                ('codproduct', models.CharField(max_length=50, verbose_name='کد کالا')),
                ('brand', models.CharField(max_length=50, verbose_name='برند کالا')),
                ('image', models.ImageField(upload_to='photo', verbose_name='عکس محصول')),
                ('imformation', models.TextField(blank=True, null=True, verbose_name='توضیحات بیشتر')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categgory', to='afapp.category', verbose_name='دسته بندی')),
            ],
        ),
    ]
