# Generated by Django 5.1 on 2025-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='costomuser',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='costomuser',
            name='lastname',
        ),
        migrations.AlterField(
            model_name='costomuser',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
    ]
