# Generated by Django 5.1 on 2024-12-17 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0002_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='discountprice',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='قیمت محصول بعد از تخفیف'),
        ),
    ]
