# Generated by Django 5.1 on 2024-12-17 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0003_alter_product_discountprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='قدرت قطع'),
        ),
    ]
