# Generated by Django 5.1 on 2024-12-17 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0005_alter_product_faz_alter_product_power_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='faz',
            field=models.CharField(max_length=50, verbose_name='مقدار فاز '),
        ),
    ]
