# Generated by Django 5.1 on 2024-12-17 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0006_alter_product_faz'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='قدرت قطع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zirname',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='محصول نول دارد؟'),
        ),
    ]
