# Generated by Django 5.1 on 2024-12-19 06:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0007_alter_product_power_alter_product_zirname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='afapp.category', verbose_name='دسته بندی'),
        ),
        migrations.AlterField(
            model_name='product',
            name='power',
            field=models.CharField(default='', max_length=50, verbose_name='قدرت قطع'),
        ),
        migrations.AlterField(
            model_name='product',
            name='zirname',
            field=models.CharField(default='', max_length=50, verbose_name='محصول نول دارد؟'),
        ),
    ]
