# Generated by Django 5.1 on 2024-12-28 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0011_product_sold_count'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aboutus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titell', models.CharField(max_length=50, verbose_name='تیتر اول')),
                ('textt', models.TextField(verbose_name='متن اول')),
                ('titelll', models.CharField(max_length=50, verbose_name='تیتر دوم')),
                ('texttt', models.TextField(verbose_name='متن دوم')),
            ],
        ),
    ]
