# Generated by Django 5.1 on 2024-12-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0012_aboutus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='texttt',
            field=models.TextField(blank=True, null=True, verbose_name='متن دوم'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='titelll',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='تیتر دوم'),
        ),
    ]
