# Generated by Django 5.1 on 2024-12-28 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0013_alter_aboutus_texttt_alter_aboutus_titelll'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='texttt',
            field=models.TextField(default='', verbose_name='متن دوم'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='titelll',
            field=models.CharField(default='', max_length=50, verbose_name='تیتر دوم'),
        ),
    ]
