# Generated by Django 5.1 on 2025-01-08 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0015_alter_aboutus_texttt_alter_aboutus_titelll'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flux',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='جریان'),
        ),
        migrations.AddField(
            model_name='product',
            name='pol',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='تعداد پل'),
        ),
    ]
