# Generated by Django 5.1 on 2025-01-08 09:37

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0017_product_image2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='imformation',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='توضیحات بیشتر'),
        ),
    ]
