# Generated by Django 5.1 on 2025-01-08 19:13

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0018_alter_product_imformation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Addres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phoone1', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('phoone2', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('phoone3', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('phoone4', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('email1', models.EmailField(max_length=254, verbose_name='ایمیل')),
                ('email2', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('email3', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('adres', ckeditor.fields.RichTextField(verbose_name='نشانی')),
                ('op', models.IntegerField()),
                ('cl', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='textt',
            field=ckeditor.fields.RichTextField(verbose_name='متن اول'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='texttt',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='متن دوم'),
        ),
    ]
