# Generated by Django 5.1 on 2025-01-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('afapp', '0019_addres_alter_aboutus_textt_alter_aboutus_texttt'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=11, unique=True, verbose_name='شماره موبایل')),
                ('creatat', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
